functionsDirectory = "C:\\Users\\user\\Desktop\\SIH 2 - Copy\\SIH 2 - Copy\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "C:\\Users\\user\\Desktop\\SIH 2 - Copy\\SIH 2 - Copy\\frontend\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm --prefix backend install && npm --prefix frontend install && npm --prefix frontend run build"
functions = "C:\\Users\\user\\Desktop\\SIH 2 - Copy\\SIH 2 - Copy\\netlify\\functions"

[build.environment]
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
included_files = ["backend/**"]
node_bundler = "esbuild"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]